{{- if and .Values.clickhouse.backup.enabled (not .Values.clickhouse.backup.password_secret_name) (not .Values.clickhouse.backup.password_sha256_hex) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.fullname" . }}-backup-credentials
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.clickhouse.backup.password | quote }}
{{- end }}
